// backend/data.js - JSON 데이터를 ES 모듈로 export
export const data = [
    {
        year: 2024,
        months: [
            {
                month: 1,
                list: [
                    {
                        date: 3,
                        type: "income",
                        category: "월급",
                        description: "1월 급여",
                        paymentMethod: "현금",
                        amount: 2100000,
                    },
                    {
                        date: 12,
                        type: "expense",
                        category: "식비",
                        description: "점심 김치찌개",
                        paymentMethod: "현금",
                        amount: 7000,
                    },
                    {
                        date: 18,
                        type: "expense",
                        category: "문화/여가",
                        description: '영화 "위시" 관람',
                        paymentMethod: "신용카드",
                        amount: 12000,
                    },
                    {
                        date: 18,
                        type: "expense",
                        category: "식비",
                        description: "영화관 팝콘 세트",
                        paymentMethod: "신용카드",
                        amount: 8500,
                    },
                    {
                        date: 24,
                        type: "expense",
                        category: "생활",
                        description: "세탁세제 대용량 구매",
                        paymentMethod: "신용카드",
                        amount: 8900,
                    },
                    {
                        date: 14,
                        amount: 2000000,
                        type: "income",
                        description: "입금 테스트",
                        paymentMethod: "현금",
                        category: "월급",
                    },
                    {
                        date: 14,
                        amount: 23131,
                        type: "income",
                        description: "입금 테스트",
                        paymentMethod: "현금",
                        category: "용돈",
                    },
                ],
            },
            {
                month: 2,
                list: [
                    {
                        date: 2,
                        type: "income",
                        category: "월급",
                        description: "2월 급여",
                        paymentMethod: "현금",
                        amount: 2100000,
                    },
                    {
                        date: 2,
                        type: "expense",
                        category: "식비",
                        description: "아침 토스트 세트",
                        paymentMethod: "현금",
                        amount: 4500,
                    },
                    {
                        date: 7,
                        type: "expense",
                        category: "식비",
                        description: "치킨 배달",
                        paymentMethod: "신용카드",
                        amount: 18500,
                    },
                    {
                        date: 7,
                        type: "expense",
                        category: "문화/여가",
                        description: "넷플릭스 영화 대여",
                        paymentMethod: "신용카드",
                        amount: 4500,
                    },
                    {
                        date: 10,
                        type: "expense",
                        category: "쇼핑/뷰티",
                        description: "샴푸·린스 세트",
                        paymentMethod: "신용카드",
                        amount: 16500,
                    },
                    {
                        date: 10,
                        type: "expense",
                        category: "생활",
                        description: "욕실 청소용품",
                        paymentMethod: "신용카드",
                        amount: 9800,
                    },
                    {
                        date: 16,
                        type: "expense",
                        category: "교통",
                        description: "지하철 충전권",
                        paymentMethod: "현금",
                        amount: 5000,
                    },
                    {
                        date: 23,
                        type: "expense",
                        category: "문화/여가",
                        description: "넷플릭스 정기결제",
                        paymentMethod: "신용카드",
                        amount: 14500,
                    },
                    {
                        date: 20,
                        amount: 300000,
                        type: "expense",
                        description: "베트남 다낭 항공비 왕복",
                        paymentMethod: "신용카드",
                        category: "교통",
                    },
                    {
                        date: 16,
                        amount: 3000,
                        type: "expense",
                        description: "버스 교통 요금",
                        paymentMethod: "신용카드",
                        category: "교통",
                    },
                ],
            },
            {
                month: 10,
                list: [
                    {
                        date: 2,
                        type: "income",
                        category: "월급",
                        description: "10월 급여",
                        paymentMethod: "현금",
                        amount: 2180000,
                    },
                    {
                        date: 19,
                        type: "expense",
                        category: "문화/여가",
                        description: "가을축제 입장권",
                        paymentMethod: "현금",
                        amount: 20000,
                    },
                    {
                        date: 23,
                        type: "expense",
                        category: "생활",
                        description: "가을 전기요금",
                        paymentMethod: "신용카드",
                        amount: 47000,
                    },
                ],
            },
        ],
    },
];

export default data;
