// 거래 내역 더미 데이터
export const items = [
  {
    id: 1,
    date: "2025-08-05",
    category: "교통",
    description: "후불 교통비 결제",
    method: "현대카드",
    type: "deposit",
    amount: "10000000",
  },
  {
    id: 2,
    date: "2025-07-04",
    category: "문화/여가",
    description: "스트리밍 서비스 정기 결제",
    method: "현대카드",
    type: "withdraw",
    amount: "10900",
  },
  {
    id: 3,
    date: "2025-08-04",
    category: "문화/여가",
    description: "스트리밍 서비스 정기 결제",
    method: "현대카드",
    type: "withdraw",
    amount: "10900",
  },
  {
    id: 4,
    date: "2025-08-04",
    category: "교통",
    description: "후불 교통비 결제",
    method: "현대카드",
    type: "withdraw",
    amount: "45340",
  },
  {
    id: 5,
    date: "2025-08-05",
    category: "문화/여가",
    description: "스트리밍 서비스 정기 결제",
    method: "현대카드",
    type: "withdraw",
    amount: "10900",
  },
  {
    id: 6,
    date: "2025-08-05",
    category: "교통",
    description: "후불 교통비 결제",
    method: "현대카드",
    type: "withdraw",
    amount: "45340",
  },
];
